---
name: Build & Release
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - name: "Download minikube"
         run: |
           curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
           sudo install minikube-linux-amd64 /usr/local/bin/minikube
       - name: "Install podman"
         run: |
            sudo apt install podman -y
       - name: "Starting minikube"
         run: |
            minikube start --driver=podman --container-runtime=containerd --extra-config=kubelet.cgroup-driver=systemd