---
name: Build & Release
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - name: "Download minikube"
         run: |
           curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
           sudo install minikube-linux-amd64 /usr/local/bin/minikube
       - name: "Install podman"
         run: |
            sudo apt install podman -y
       - name: "Starting minikube"
         run: |
            minikube start --driver=podman --container-runtime=containerd --extra-config=kubelet.cgroup-driver=systemd 
            minikube cache add gcr.io/k8s-minikube/storage-provisioner:v5
            minikube cache add registry.k8s.io/coredns/coredns:v1.9.3
            minikube cache add registry.k8s.io/pause:3.9
            minikube cache add registry.k8s.io/kube-proxy:v1.26.1
            minikube cache add registry.k8s.io/kube-controller-manager:v1.26.1
            minikube cache add registry.k8s.io/kube-apiserver:v1.26.1
            minikube cache add registry.k8s.io/etcd:3.5.6-0
            minikube cache add registry.k8s.io/kube-scheduler:v1.26.1

            whoami
            podman images
            ls -al /home/runner/.minikube/cache/*
       - name: "tar the cache directory"
         run: |
            tar -zcvf minikube.tgz /home/runner/.minikube/cache
            
            ls -l minikube.tgz
            pwd 
            ls -l ${{ github.workspace }}
       - uses: actions/upload-artifact@v3
         with:
            name: minikube
            path: "${{ github.workspace }}/minikube.tgz"
